# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pp_spider.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pp_spider.proto',
  package='pp',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fpp_spider.proto\x12\x02pp\".\n\x0cPPSpiderResp\x12\x1e\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x10.pp.PPSpiderBody\"G\n\x0cPPSpiderBody\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04link\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\"c\n\x0bPPSpiderReq\x12%\n\x0csection_type\x18\x01 \x01(\x0e\x32\x0f.pp.SectionType\x12\x0c\n\x04page\x18\x02 \x01(\r\x12\x1f\n\tnews_type\x18\x03 \x01(\x0e\x32\x0c.pp.NewsType*c\n\x0bSectionType\x12\x05\n\x01_\x10\x00\x12\x0c\n\x08ST_TEACH\x10$\x12\x0c\n\x07ST_NEWS\x10\xef\x01\x12\x11\n\x0cST_EQUIPMENT\x10\xe3\x01\x12\x11\n\rST_GAME_VIDEO\x10\x02\x12\x0b\n\x06ST_ASK\x10\xc9\x02*T\n\x08NewsType\x12\n\n\x06NT_ALL\x10\x00\x12\x0c\n\x07NT_GAME\x10\xe5\x01\x12\x0e\n\tNT_PLAYER\x10\xe7\x01\x12\x11\n\x0cNT_EQUIPMENT\x10\xe8\x01\x12\x0b\n\x06NT_FUN\x10\xe6\x01\x32;\n\x08PPSpider\x12/\n\x08\x46\x65tchPPW\x12\x0f.pp.PPSpiderReq\x1a\x10.pp.PPSpiderResp\"\x00\x62\x06proto3'
)

_SECTIONTYPE = _descriptor.EnumDescriptor(
  name='SectionType',
  full_name='pp.SectionType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='_', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ST_TEACH', index=1, number=36,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ST_NEWS', index=2, number=239,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ST_EQUIPMENT', index=3, number=227,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ST_GAME_VIDEO', index=4, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ST_ASK', index=5, number=329,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=245,
  serialized_end=344,
)
_sym_db.RegisterEnumDescriptor(_SECTIONTYPE)

SectionType = enum_type_wrapper.EnumTypeWrapper(_SECTIONTYPE)
_NEWSTYPE = _descriptor.EnumDescriptor(
  name='NewsType',
  full_name='pp.NewsType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NT_ALL', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NT_GAME', index=1, number=229,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NT_PLAYER', index=2, number=231,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NT_EQUIPMENT', index=3, number=232,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NT_FUN', index=4, number=230,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=346,
  serialized_end=430,
)
_sym_db.RegisterEnumDescriptor(_NEWSTYPE)

NewsType = enum_type_wrapper.EnumTypeWrapper(_NEWSTYPE)
_ = 0
ST_TEACH = 36
ST_NEWS = 239
ST_EQUIPMENT = 227
ST_GAME_VIDEO = 2
ST_ASK = 329
NT_ALL = 0
NT_GAME = 229
NT_PLAYER = 231
NT_EQUIPMENT = 232
NT_FUN = 230



_PPSPIDERRESP = _descriptor.Descriptor(
  name='PPSpiderResp',
  full_name='pp.PPSpiderResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='pp.PPSpiderResp.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=69,
)


_PPSPIDERBODY = _descriptor.Descriptor(
  name='PPSpiderBody',
  full_name='pp.PPSpiderBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='pp.PPSpiderBody.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='link', full_name='pp.PPSpiderBody.link', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='pp.PPSpiderBody.time', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date', full_name='pp.PPSpiderBody.date', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=142,
)


_PPSPIDERREQ = _descriptor.Descriptor(
  name='PPSpiderReq',
  full_name='pp.PPSpiderReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='section_type', full_name='pp.PPSpiderReq.section_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='page', full_name='pp.PPSpiderReq.page', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='news_type', full_name='pp.PPSpiderReq.news_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=243,
)

_PPSPIDERRESP.fields_by_name['data'].message_type = _PPSPIDERBODY
_PPSPIDERREQ.fields_by_name['section_type'].enum_type = _SECTIONTYPE
_PPSPIDERREQ.fields_by_name['news_type'].enum_type = _NEWSTYPE
DESCRIPTOR.message_types_by_name['PPSpiderResp'] = _PPSPIDERRESP
DESCRIPTOR.message_types_by_name['PPSpiderBody'] = _PPSPIDERBODY
DESCRIPTOR.message_types_by_name['PPSpiderReq'] = _PPSPIDERREQ
DESCRIPTOR.enum_types_by_name['SectionType'] = _SECTIONTYPE
DESCRIPTOR.enum_types_by_name['NewsType'] = _NEWSTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PPSpiderResp = _reflection.GeneratedProtocolMessageType('PPSpiderResp', (_message.Message,), {
  'DESCRIPTOR' : _PPSPIDERRESP,
  '__module__' : 'pp_spider_pb2'
  # @@protoc_insertion_point(class_scope:pp.PPSpiderResp)
  })
_sym_db.RegisterMessage(PPSpiderResp)

PPSpiderBody = _reflection.GeneratedProtocolMessageType('PPSpiderBody', (_message.Message,), {
  'DESCRIPTOR' : _PPSPIDERBODY,
  '__module__' : 'pp_spider_pb2'
  # @@protoc_insertion_point(class_scope:pp.PPSpiderBody)
  })
_sym_db.RegisterMessage(PPSpiderBody)

PPSpiderReq = _reflection.GeneratedProtocolMessageType('PPSpiderReq', (_message.Message,), {
  'DESCRIPTOR' : _PPSPIDERREQ,
  '__module__' : 'pp_spider_pb2'
  # @@protoc_insertion_point(class_scope:pp.PPSpiderReq)
  })
_sym_db.RegisterMessage(PPSpiderReq)



_PPSPIDER = _descriptor.ServiceDescriptor(
  name='PPSpider',
  full_name='pp.PPSpider',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=432,
  serialized_end=491,
  methods=[
  _descriptor.MethodDescriptor(
    name='FetchPPW',
    full_name='pp.PPSpider.FetchPPW',
    index=0,
    containing_service=None,
    input_type=_PPSPIDERREQ,
    output_type=_PPSPIDERRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PPSPIDER)

DESCRIPTOR.services_by_name['PPSpider'] = _PPSPIDER

# @@protoc_insertion_point(module_scope)
