# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rpc.pp.pp_spider_pb2 as pp__spider__pb2


class PPSpiderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchPPW = channel.unary_unary(
                '/pp.PPSpider/FetchPPW',
                request_serializer=pp__spider__pb2.PPSpiderReq.SerializeToString,
                response_deserializer=pp__spider__pb2.PPSpiderResp.FromString,
                )


class PPSpiderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FetchPPW(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PPSpiderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FetchPPW': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchPPW,
                    request_deserializer=pp__spider__pb2.PPSpiderReq.FromString,
                    response_serializer=pp__spider__pb2.PPSpiderResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pp.PPSpider', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PPSpider(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FetchPPW(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pp.PPSpider/FetchPPW',
            pp__spider__pb2.PPSpiderReq.SerializeToString,
            pp__spider__pb2.PPSpiderResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
