# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rpc.zhihu.zhihu_spider_pb2 as zhihu__spider__pb2


class ZhiHuSpiderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchHot = channel.unary_unary(
                '/zhihu.ZhiHuSpider/FetchHot',
                request_serializer=zhihu__spider__pb2.ZhiHuSpiderReq.SerializeToString,
                response_deserializer=zhihu__spider__pb2.ZhiHuSpiderResp.FromString,
                )


class ZhiHuSpiderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FetchHot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ZhiHuSpiderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FetchHot': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchHot,
                    request_deserializer=zhihu__spider__pb2.ZhiHuSpiderReq.FromString,
                    response_serializer=zhihu__spider__pb2.ZhiHuSpiderResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zhihu.ZhiHuSpider', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ZhiHuSpider(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FetchHot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zhihu.ZhiHuSpider/FetchHot',
            zhihu__spider__pb2.ZhiHuSpiderReq.SerializeToString,
            zhihu__spider__pb2.ZhiHuSpiderResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
