# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zhihu_spider.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='zhihu_spider.proto',
  package='zhihu',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12zhihu_spider.proto\x12\x05zhihu\"\x10\n\x0eZhiHuSpiderReq\"7\n\x0fZhiHuSpiderResp\x12$\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x16.zhihu.ZhiHuSpiderItem\"\xb5\x01\n\x0fZhiHuSpiderItem\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x0f\n\x07\x63reated\x18\x03 \x01(\x04\x12\x14\n\x0c\x61nswer_count\x18\x04 \x01(\r\x12\x16\n\x0e\x66ollower_count\x18\x05 \x01(\r\x12\x15\n\rcomment_count\x18\x06 \x01(\r\x12\r\n\x05\x62rief\x18\x07 \x01(\t\x12\x11\n\tthumbnail\x18\x08 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\t \x01(\t2J\n\x0bZhiHuSpider\x12;\n\x08\x46\x65tchHot\x12\x15.zhihu.ZhiHuSpiderReq\x1a\x16.zhihu.ZhiHuSpiderResp\"\x00\x62\x06proto3'
)




_ZHIHUSPIDERREQ = _descriptor.Descriptor(
  name='ZhiHuSpiderReq',
  full_name='zhihu.ZhiHuSpiderReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=45,
)


_ZHIHUSPIDERRESP = _descriptor.Descriptor(
  name='ZhiHuSpiderResp',
  full_name='zhihu.ZhiHuSpiderResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='zhihu.ZhiHuSpiderResp.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=102,
)


_ZHIHUSPIDERITEM = _descriptor.Descriptor(
  name='ZhiHuSpiderItem',
  full_name='zhihu.ZhiHuSpiderItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='zhihu.ZhiHuSpiderItem.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='zhihu.ZhiHuSpiderItem.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='created', full_name='zhihu.ZhiHuSpiderItem.created', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='answer_count', full_name='zhihu.ZhiHuSpiderItem.answer_count', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='follower_count', full_name='zhihu.ZhiHuSpiderItem.follower_count', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='comment_count', full_name='zhihu.ZhiHuSpiderItem.comment_count', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='brief', full_name='zhihu.ZhiHuSpiderItem.brief', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='thumbnail', full_name='zhihu.ZhiHuSpiderItem.thumbnail', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='detail', full_name='zhihu.ZhiHuSpiderItem.detail', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=286,
)

_ZHIHUSPIDERRESP.fields_by_name['data'].message_type = _ZHIHUSPIDERITEM
DESCRIPTOR.message_types_by_name['ZhiHuSpiderReq'] = _ZHIHUSPIDERREQ
DESCRIPTOR.message_types_by_name['ZhiHuSpiderResp'] = _ZHIHUSPIDERRESP
DESCRIPTOR.message_types_by_name['ZhiHuSpiderItem'] = _ZHIHUSPIDERITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ZhiHuSpiderReq = _reflection.GeneratedProtocolMessageType('ZhiHuSpiderReq', (_message.Message,), {
  'DESCRIPTOR' : _ZHIHUSPIDERREQ,
  '__module__' : 'zhihu_spider_pb2'
  # @@protoc_insertion_point(class_scope:zhihu.ZhiHuSpiderReq)
  })
_sym_db.RegisterMessage(ZhiHuSpiderReq)

ZhiHuSpiderResp = _reflection.GeneratedProtocolMessageType('ZhiHuSpiderResp', (_message.Message,), {
  'DESCRIPTOR' : _ZHIHUSPIDERRESP,
  '__module__' : 'zhihu_spider_pb2'
  # @@protoc_insertion_point(class_scope:zhihu.ZhiHuSpiderResp)
  })
_sym_db.RegisterMessage(ZhiHuSpiderResp)

ZhiHuSpiderItem = _reflection.GeneratedProtocolMessageType('ZhiHuSpiderItem', (_message.Message,), {
  'DESCRIPTOR' : _ZHIHUSPIDERITEM,
  '__module__' : 'zhihu_spider_pb2'
  # @@protoc_insertion_point(class_scope:zhihu.ZhiHuSpiderItem)
  })
_sym_db.RegisterMessage(ZhiHuSpiderItem)



_ZHIHUSPIDER = _descriptor.ServiceDescriptor(
  name='ZhiHuSpider',
  full_name='zhihu.ZhiHuSpider',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=288,
  serialized_end=362,
  methods=[
  _descriptor.MethodDescriptor(
    name='FetchHot',
    full_name='zhihu.ZhiHuSpider.FetchHot',
    index=0,
    containing_service=None,
    input_type=_ZHIHUSPIDERREQ,
    output_type=_ZHIHUSPIDERRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ZHIHUSPIDER)

DESCRIPTOR.services_by_name['ZhiHuSpider'] = _ZHIHUSPIDER

# @@protoc_insertion_point(module_scope)
